//#include "stm32f10x.h"				//we use stm32f100rb

//STM32F100RB DDS waveform generator
//Using the DAC/TIMER1 to generate waveforms
//See Atmel DOC2542
//MCU runs at 24Mhz
//PWM generated by CLK/1, or CLK / 1
//ISR need 20 ticks for overhead + 40 ticks for math / accumulator

#include "gpio.h"						//we use stm32f100rb
#include "dac.h"						//we use dac - dual channel, 12-bit, right aligned
#include "tim7.h"						//we use tim7 as the time base

//hardware configuration
#define OUT_PORT		GPIOB
#define OUT_DDR			GPIOB
#define OUT1			((1<<1) | (1<<0))	//OC1A = PB1, _OC1A = PB0
#define OUT2			((1<<4) | (1<<3))	//OC1B = PB4, _OC1B = PB3
#define DDS_STEPPING1	(DDS_100hz)			//phase stepping for desired output frequency on Ch1
#define DDS_STEPPING2	(DDS_100hz)			//phase stepping for desired output frequency on Ch2
#define DDS_DPHASE		1000ul			//phase difference between output1 and output2.
//#define DDS_USEPLL							//comment out if PLL is not used
//when PLL is used, prescaler = 2:1, PCLK = 64Mhz
//when PLL is not used, prescaler = 1:1, CLK = 8Mhz
#define DDS_WAVEOUT1()	DDS_SINE(dds_ptr1)			//set the output waveform. _SINE(), _SAWTOOTH(), _TRIANGLE(), _SQUARE(), _ECG(), _SINEABS()
#define DDS_WAVEOUT2()	DDS_SINE(dds_ptr2)			//set the output waveform. _SINE(), _SAWTOOTH(), _TRIANGLE(), _SQUARE(), _ECG(), _SINEABS()
#define DDS_TICK		150				//dds ticks per output period - 150 ticks minimum @ 24MIPS

//for debug only
#define LED_PORT		GPIOC
#define LED_DDR			GPIOC
#define LED				(1<<8)			//blue led on pc8, green led on pc9
//end hardware configuration

//global defines
//frequency calculations
//Stepping = Fout * 2^32 / Fclk, for 32-bit phase accumulators
//Fclk = 8Mhz / 2 = 4Mhz
#define DDS_0hz1		(DDS_1hz  /10)		//phase stepping for 0.1Hz
#define DDS_0hz2		(DDS_1hz  / 5)		//phase stepping for 0.5Hz
#define DDS_0hz25		(DDS_1hz  / 4)		//phase stepping for 0.25Hz
#define DDS_0hz5		(DDS_1hz   / 2)		//phase stepping for 0.5Hz
#define DDS_1hz			(DDS_10hz  / 10)	//phase stepping for 1Hz
#define DDS_2hz			(DDS_10hz  / 5)		//phase stepping for 2Hz
#define DDS_5hz			(DDS_10hz  / 2)		//phase stepping for 5Hz
#define DDS_10hz		(DDS_100hz /10)		//phase stepping for 10Hz
#define DDS_20hz		(DDS_100hz / 5)		//phase stepping for 20Hz
#define DDS_25hz		(DDS_100hz / 4)		//phase stepping for 25Hz
#define DDS_50hz		(DDS_100hz / 2)		//phase stepping for 50Hz
#define DDS_100hz		(DDS_1Khz  /10)		//phase stepping for 100Hz
#define DDS_200hz		(DDS_1Khz  / 5)		//phase stepping for 200Hz
#define DDS_250hz		(DDS_1Khz  / 4)		//phase stepping for 250Hz
#define DDS_500hz		(DDS_1Khz  / 2)		//phase stepping for 500Hz
#define DDS_1Khz		(DDS_10Khz /10)		//phase stepping for 1Khz
#define DDS_2Khz		(DDS_10Khz / 5)		//phase stepping for 2Khz
#define DDS_2K5hz		(DDS_10Khz / 4)		//phase stepping for 2.5Khz
#define DDS_5Khz		(DDS_10Khz / 2)		//phase stepping for 5Khz
#define DDS_10Khz		(DDS_100Khz /10)	//phase stepping for 10Khz
#define DDS_20Khz		(DDS_100Khz / 5)	//phase stepping for 20Khz
#define DDS_25Khz		(DDS_100Khz / 4)	//phase stepping for 25Khz
#define DDS_50Khz		(DDS_100Khz / 2)	//phase stepping for 50Khz
#define DDS_100Khz		(2684354560ul)		//phase stepping for 100Khz
//#define DDS_200Khz		3579139413ul		//phase stepping for 200Khz, 24Mhz oscillator, 100 tick period -> stepping = (Fout * 2^32 / (24Mhz / 100)

//pick the output waveform
#define DDS_SINE(ptr)		ptr = dds_sin;	//output sine wave
#define DDS_SAWTOOTH(ptr)	ptr = dds_sawtooth;	//output sawtooth wave
#define DDS_TRIANGLE(ptr)	ptr = dds_triangle;	//output triangle wave
#define DDS_SQUARE(ptr)		ptr = dds_square;	//output square wave
#define DDS_ECG(ptr)		ptr = dds_ecg;		//output ecg wave
#define DDS_SINEABS(ptr)	ptr = dds_sineabs;	//output rectified sine wave

#define PROGMEM								//for compatability reasons (ported from AVR where program space is used to store waveform data)

//global variables
//for DDS Ch1
volatile uint32_t dds1_accumulator;			//phase accumulator
uint8_t *dds1_msb;				//points to dds_accumlator's MSB
volatile uint16_t val1;				//duty cycle, shadow variable - not actually needed for ATtiny
const uint16_t *dds_ptr1;					//wave table pointer
//for DDS Ch2
volatile uint32_t dds2_accumulator;			//phase accumulator
uint8_t *dds2_msb;				//points to dds_accumlator's MSB
volatile uint16_t val2;				//duty cycle, shadow variable - not actually needed for ATtiny
const uint16_t *dds_ptr2;					//wave table pointer
//waveforms, 256 pints
const uint16_t dds_sin[] PROGMEM = {
	2048,	2098,	2148,	2198,	2248,	2297,	2347,	2396,
	2446,	2495,	2543,	2592,	2640,	2687,	2735,	2781,
	2828,	2874,	2919,	2964,	3009,	3053,	3096,	3138,
	3180,	3221,	3262,	3302,	3341,	3379,	3417,	3453,
	3489,	3524,	3558,	3591,	3623,	3655,	3685,	3714,
	3743,	3770,	3796,	3821,	3845,	3868,	3890,	3911,
	3931,	3949,	3967,	3983,	3998,	4012,	4025,	4036,
	4047,	4056,	4064,	4071,	4076,	4080,	4084,	4085,
	4086,	4085,	4084,	4080,	4076,	4071,	4064,	4056,
	4047,	4036,	4025,	4012,	3998,	3983,	3967,	3949,
	3931,	3911,	3890,	3868,	3845,	3821,	3796,	3770,
	3743,	3714,	3685,	3655,	3623,	3591,	3558,	3524,
	3489,	3453,	3417,	3379,	3341,	3302,	3262,	3221,
	3180,	3138,	3096,	3053,	3009,	2964,	2919,	2874,
	2828,	2781,	2735,	2687,	2640,	2592,	2543,	2495,
	2446,	2396,	2347,	2297,	2248,	2198,	2148,	2098,
	2048,	1998,	1948,	1898,	1848,	1799,	1749,	1700,
	1650,	1601,	1553,	1504,	1456,	1409,	1361,	1315,
	1268,	1222,	1177,	1132,	1087,	1043,	1000,	958,
	916,	875,	834,	794,	755,	717,	679,	643,
	607,	572,	538,	505,	473,	441,	411,	382,
	353,	326,	300,	275,	251,	228,	206,	185,
	165,	147,	129,	113,	98,	84,	71,	60,
	49,	40,	32,	25,	20,	16,	12,	11,
	10,	11,	12,	16,	20,	25,	32,	40,
	49,	60,	71,	84,	98,	113,	129,	147,
	165,	185,	206,	228,	251,	275,	300,	326,
	353,	382,	411,	441,	473,	505,	538,	572,
	607,	643,	679,	717,	755,	794,	834,	875,
	916,	958,	1000,	1043,	1087,	1132,	1177,	1222,
	1268,	1315,	1361,	1409,	1456,	1504,	1553,	1601,
	1650,	1700,	1749,	1799,	1848,	1898,	1948,	1998,
};

const uint16_t dds_triangle[] PROGMEM = {
	10,	42,	74,	106,	138,	170,	202,	233,
	265,	297,	329,	361,	393,	425,	457,	489,
	521,	553,	585,	617,	648,	680,	712,	744,
	776,	808,	840,	872,	904,	936,	968,	1000,
	1032,	1063,	1095,	1127,	1159,	1191,	1223,	1255,
	1287,	1319,	1351,	1383,	1415,	1446,	1478,	1510,
	1542,	1574,	1606,	1638,	1670,	1702,	1734,	1766,
	1798,	1830,	1861,	1893,	1925,	1957,	1989,	2021,
	2053,	2085,	2117,	2149,	2181,	2213,	2245,	2276,
	2308,	2340,	2372,	2404,	2436,	2468,	2500,	2532,
	2564,	2596,	2628,	2660,	2691,	2723,	2755,	2787,
	2819,	2851,	2883,	2915,	2947,	2979,	3011,	3043,
	3075,	3106,	3138,	3170,	3202,	3234,	3266,	3298,
	3330,	3362,	3394,	3426,	3458,	3489,	3521,	3553,
	3585,	3617,	3649,	3681,	3713,	3745,	3777,	3809,
	3841,	3873,	3904,	3936,	3968,	4000,	4032,	4064,
	4064,	4032,	4000,	3968,	3936,	3904,	3873,	3841,
	3809,	3777,	3745,	3713,	3681,	3649,	3617,	3585,
	3553,	3521,	3489,	3458,	3426,	3394,	3362,	3330,
	3298,	3266,	3234,	3202,	3170,	3138,	3106,	3075,
	3043,	3011,	2979,	2947,	2915,	2883,	2851,	2819,
	2787,	2755,	2723,	2691,	2660,	2628,	2596,	2564,
	2532,	2500,	2468,	2436,	2404,	2372,	2340,	2308,
	2276,	2245,	2213,	2181,	2149,	2117,	2085,	2053,
	2021,	1989,	1957,	1925,	1893,	1861,	1830,	1798,
	1766,	1734,	1702,	1670,	1638,	1606,	1574,	1542,
	1510,	1478,	1446,	1415,	1383,	1351,	1319,	1287,
	1255,	1223,	1191,	1159,	1127,	1095,	1063,	1032,
	1000,	968,	936,	904,	872,	840,	808,	776,
	744,	712,	680,	648,	617,	585,	553,	521,
	489,	457,	425,	393,	361,	329,	297,	265,
	233,	202,	170,	138,	106,	74,		42,		10,
};

const uint16_t dds_sawtooth[] PROGMEM = {
	10,	26,	42,	58,	74,	90,	106,	122,
	138,	154,	170,	186,	202,	217,	233,	249,
	265,	281,	297,	313,	329,	345,	361,	377,
	393,	409,	425,	441,	457,	473,	489,	505,
	521,	537,	553,	569,	585,	601,	617,	632,
	648,	664,	680,	696,	712,	728,	744,	760,
	776,	792,	808,	824,	840,	856,	872,	888,
	904,	920,	936,	952,	968,	984,	1000,	1016,
	1032,	1047,	1063,	1079,	1095,	1111,	1127,	1143,
	1159,	1175,	1191,	1207,	1223,	1239,	1255,	1271,
	1287,	1303,	1319,	1335,	1351,	1367,	1383,	1399,
	1415,	1431,	1446,	1462,	1478,	1494,	1510,	1526,
	1542,	1558,	1574,	1590,	1606,	1622,	1638,	1654,
	1670,	1686,	1702,	1718,	1734,	1750,	1766,	1782,
	1798,	1814,	1830,	1846,	1861,	1877,	1893,	1909,
	1925,	1941,	1957,	1973,	1989,	2005,	2021,	2037,
	2053,	2069,	2085,	2101,	2117,	2133,	2149,	2165,
	2181,	2197,	2213,	2229,	2245,	2260,	2276,	2292,
	2308,	2324,	2340,	2356,	2372,	2388,	2404,	2420,
	2436,	2452,	2468,	2484,	2500,	2516,	2532,	2548,
	2564,	2580,	2596,	2612,	2628,	2644,	2660,	2675,
	2691,	2707,	2723,	2739,	2755,	2771,	2787,	2803,
	2819,	2835,	2851,	2867,	2883,	2899,	2915,	2931,
	2947,	2963,	2979,	2995,	3011,	3027,	3043,	3059,
	3075,	3090,	3106,	3122,	3138,	3154,	3170,	3186,
	3202,	3218,	3234,	3250,	3266,	3282,	3298,	3314,
	3330,	3346,	3362,	3378,	3394,	3410,	3426,	3442,
	3458,	3474,	3489,	3505,	3521,	3537,	3553,	3569,
	3585,	3601,	3617,	3633,	3649,	3665,	3681,	3697,
	3713,	3729,	3745,	3761,	3777,	3793,	3809,	3825,
	3841,	3857,	3873,	3889,	3904,	3920,	3936,	3952,
	3968,	3984,	4000,	4016,	4032,	4048,	4064,	4080,
};

const uint16_t dds_square[] PROGMEM = {
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	4086,	4086,	4086,	4086,	4086,	4086,	4086,	4086,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
	10,	10,	10,	10,	10,	10,	10,	10,
};

//ecg waveform
const uint16_t dds_ecg[]={
	1172,	1188,	1204,	1204,	1188,	1172,	1172,	1172,	1172,	1156,	1140,	1109,	1093,	1077,	1077,	1077,
	1093,	1093,	1077,	1045,	997,	981,	949,	918,	902,	886,	886,	870,	870,	870,	886,	886,
	886,	886,	886,	886,	870,	854,	822,	806,	790,	790,	838,	981,	1236,	1618,	2112,	2701,
	3306,	3799,	4070,	4054,	3736,	3163,	2462,	1745,	1093,	599,	281,	90,	10,	26,	106,	217,
	328,	456,	583,	726,	838,	918,	981,	1029,	1045,	1061,	1077,	1093,	1093,	1109,	1125,	1140,
	1140,	1140,	1140,	1140,	1140,	1140,	1140,	1156,	1156,	1156,	1172,	1172,	1188,	1204,	1204,	1220,
	1236,	1252,	1268,	1284,	1300,	1316,	1332,	1347,	1379,	1411,	1459,	1491,	1539,	1570,	1602,	1634,
	1666,	1714,	1745,	1793,	1841,	1889,	1937,	1968,	2000,	2016,	2032,	2032,	2032,	2032,	2032,	2016,
	2000,	1984,	1937,	1905,	1857,	1809,	1745,	1682,	1634,	1570,	1523,	1475,	1427,	1395,	1347,	1300,
	1268,	1236,	1220,	1204,	1188,	1172,	1156,	1125,	1109,	1093,	1077,	1077,	1077,	1093,	1093,	1093,
	1109,	1109,	1109,	1109,	1109,	1109,	1109,	1125,	1140,	1156,	1172,	1172,	1188,	1188,	1204,	1204,
	1204,	1204,	1204,	1204,	1188,	1188,	1172,	1172,	1172,	1172,	1156,	1156,	1156,	1140,	1140,	1140,
	1140,	1140,	1140,	1140,	1125,	1125,	1125,	1109,	1109,	1109,	1109,	1109,	1125,	1125,	1125,	1109,
	1093,	1093,	1077,	1077,	1077,	1077,	1061,	1061,	1061,	1045,	1045,	1045,	1045,	1045,	1045,	1045,
	1045,	1029,	1029,	1013,	1013,	1029,	1029,	1045,	1045,	1045,	1045,	1045,	1045,	1045,	1029,	1029,
	1029,	1029,	1029,	1029,	1029,	1029,	1045,	1045,	1045,	1061,	1077,	1093,	1109,	1140,	1156,	1172,

};

//half sine wave - rectified sine wave
const uint16_t dds_sineabs[]={
	10,	110,	210,	310,	410,	509,	608,	707,
	805,	903,	1000,	1097,	1193,	1289,	1383,	1477,
	1570,	1662,	1753,	1843,	1931,	2019,	2105,	2191,
	2275,	2357,	2438,	2518,	2596,	2672,	2747,	2821,
	2892,	2962,	3030,	3096,	3161,	3223,	3284,	3342,
	3399,	3454,	3506,	3556,	3605,	3651,	3695,	3736,
	3776,	3813,	3848,	3880,	3910,	3938,	3964,	3987,
	4008,	4026,	4042,	4055,	4066,	4075,	4081,	4085,
	4086,	4085,	4081,	4075,	4066,	4055,	4042,	4026,
	4008,	3987,	3964,	3938,	3910,	3880,	3848,	3813,
	3776,	3736,	3695,	3651,	3605,	3556,	3506,	3454,
	3399,	3342,	3284,	3223,	3161,	3096,	3030,	2962,
	2892,	2821,	2747,	2672,	2596,	2518,	2438,	2357,
	2275,	2191,	2105,	2019,	1931,	1843,	1753,	1662,
	1570,	1477,	1383,	1289,	1193,	1097,	1000,	903,
	805,	707,	608,	509,	410,	310,	210,	110,
	10,	110,	210,	310,	410,	509,	608,	707,
	805,	903,	1000,	1097,	1193,	1289,	1383,	1477,
	1570,	1662,	1753,	1843,	1931,	2019,	2105,	2191,
	2275,	2357,	2438,	2518,	2596,	2672,	2747,	2821,
	2892,	2962,	3030,	3096,	3161,	3223,	3284,	3342,
	3399,	3454,	3506,	3556,	3605,	3651,	3695,	3736,
	3776,	3813,	3848,	3880,	3910,	3938,	3964,	3987,
	4008,	4026,	4042,	4055,	4066,	4075,	4081,	4085,
	4086,	4085,	4081,	4075,	4066,	4055,	4042,	4026,
	4008,	3987,	3964,	3938,	3910,	3880,	3848,	3813,
	3776,	3736,	3695,	3651,	3605,	3556,	3506,	3454,
	3399,	3342,	3284,	3223,	3161,	3096,	3030,	2962,
	2892,	2821,	2747,	2672,	2596,	2518,	2438,	2357,
	2275,	2191,	2105,	2019,	1931,	1843,	1753,	1662,
	1570,	1477,	1383,	1289,	1193,	1097,	1000,	903,
	805,	707,	608,	509,	410,	310,	210,	110,

};
//dds output routine - called out by TIM7 ISR periodically
void dds_out(void) {
    //clera the flag - done automatically
    //IO_FLP(LED_PORT, LED);				//for debug only

    //update the DAC1/2
    //DAC1Write(val1);					//output on DAC1
    //DAC2Write(val2);					//output on DAC1
	DAC->DHR12R1 = val1;				// & 0x0ffful;		//bound the value to [0..4095]
	DAC->DHR12R2 = val2;				// & 0x0ffful;		//bound the value to [0..4095]
	DAC->SWTRIGR|= (1<<0) | (1<<1);		//output on DAC1/2 - cleared by hardware

	//advance the accumulators
    dds1_accumulator += DDS_STEPPING1; val1 = dds_ptr1[*dds1_msb];		//advance phase accumulator + pick up the next value
    dds2_accumulator += DDS_STEPPING2; val2 = dds_ptr2[*dds2_msb];		//advance phase accumulator + pick up the next value
}

//reset the dds
void dds_init(void) {
    //reset the output pins
    IO_OUT(OUT_DDR, OUT1 | OUT2);		//OUT1/2 as output

    //reset the variables
    dds1_msb = (uint8_t *) (&dds1_accumulator) + 3;	//point dds_msb to dds_accumlator's MSB
    dds2_msb = (uint8_t *) (&dds2_accumulator) + 3;	//point dds_msb to dds_accumlator's MSB
    DDS_WAVEOUT1();							//set the output waveform for CH1
    DDS_WAVEOUT2();							//set the output waveform for Ch2
    dds1_accumulator = 0;					//reset the phase accumulator
    dds2_accumulator = dds1_accumulator + DDS_DPHASE;
    val1 = dds_ptr1[+*dds1_msb];			//initialize the duty cycle
    val2 = dds_ptr2[+*dds2_msb];			//initialize the duty cycle

    //set up dac - dual channel, right alighted, 12-bit
    dac_init();								//reset the dac
    //set io pins for gpioa4/dac1 and gpioa5/dac2
    IO_AFPP(GPIOA, 1<<4);					//GIO_AFPP(GPIO_PinDef[4].gpio, GPIO_PinDef[4].mask);	//configure pin 4 as afio output
	IO_AFPP(GPIOA, 1<<5);					//GIO_AFPP(GPIO_PinDef[5].gpio, GPIO_PinDef[5].mask);	//configure pin 5 as afio output


    //set up timer
    tim7_init(1);						//reset tim7, prescaler 1:1
    tim7_setpr(DDS_TICK);					//set the period to 100, max 0xffff
    tim7_act(dds_out);						//install user handler

}


int main(void) {

    mcu_init();								//reset the mcu
    dds_init();								//initialize the dds
    IO_OUT(LED_DDR, LED);					//led as output - debug only

    ei();									//enable interrupts
    while(1) {								//empty loop - execution done via interrupts
        IO_FLP(LED_PORT, LED);				//for performance measurement
        //24Mhz SystemCoreClock
        //-O1 optimization: 1.333Mhz vs. 239.9Khz -> DDS routine takes (1-239.9Khz / 1333Khz) * 24MIPS = 20MIPS
        //-O3 optimization: 1.333Mhz vs. 293.3Khz -
    }

    return 0;
}

